CREATE TABLE INFO(
   INFO_SQ NUMBER PRIMARY KEY,
   INFO_CATEGORY CHAR(20) CHECK(INFO_CATEGORY IN('설명회','박람회','상담회'))NOT NULL,
   INFO_TITLE VARCHAR2(50 BYTE),
   INFO_DATE VARCHAR2(100 BYTE),
   INFO_TIME  VARCHAR2(100 BYTE),
   MEMBER_NUM NUMBER NOT NULL,
   
   CONSTRAINT FK_INFO FOREIGN KEY(MEMBER_NUM) REFERENCES MEMBER(MEMBER_SQ) ON DELETE CASCADE
);
INSERT INTO INFO VALUES (INFO_SQ.NEXTVAL,'설명회','제목','11월11일','오전10:50','주소입니다',999,'내용1',1);
INSERT INTO INFO VALUES (INFO_SQ.NEXTVAL,'박람회','제목2','11월12일','오전11:50','주소2',999,'내용2',1);
INSERT INTO INFO VALUES (INFO_SQ.NEXTVAL,'상담회','제목3','11월13일','오전12:50','주소3',999,'내용3',1);
ALTER TABLE INFO ADD (INFO_CONTENT VARCHAR2(500));

select * from INFO;
--drop table INFO;
COMMIT;
ALTER TABLE INFO ADD(INFO_COUNT VARCHAR2(500));

        COMMENT ON COLUMN "INFO"."INFO_SQ" IS '취업정보시퀀스';
        COMMENT ON COLUMN "INFO"."INFO_CATEGORY" IS '취업정보카테고리';
        COMMENT ON COLUMN "INFO"."INFO_TITLE" IS '취업정보기업명';
        COMMENT ON COLUMN "INFO"."INFO_DATE" IS '취업정보날짜';
        COMMENT ON COLUMN "INFO"."INFO_TIME" IS '취업정보시간';
        COMMENT ON COLUMN "INFO"."MEMBER_NUM" IS '회원시퀀스';
        COMMENT ON COLUMN "INFO"."INFO_CONTENT" IS '내용';
        COMMENT ON COLUMN "INFO"."INFO_COUNT" IS '조회수';
           
          SELECT * FROM INFO;
         
         --컬럼삭제
         ALTER TABLE INFO DROP COLUMN INFO_ADDRESS;
          
-- 시퀀스
CREATE SEQUENCE INFO_SQ
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

